name: goorani
description: music

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.1
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.1.1
  flutter_svg: ^2.0.5
<<<<<<< HEAD
=======
  flutter_bloc: ^8.1.3
  video_viewer: ^1.2.7
>>>>>>> 9e54a20 (music gorani player)

  chewie: ^1.7.4
  video_player: ^2.8.1
  provider: ^6.1.1
  scroll_bottom_navigation_bar: ^4.0.0
  
  easy_search_bar: ^2.5.0
  
  audio_video_progress_bar: ^2.0.1
  just_audio: ^0.9.36
  audioplayers: ^5.2.1
  miniplayer: ^1.0.1
  http: ^1.1.2
  dio: ^5.4.0
  sliding_up_panel: ^2.0.0+1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter






flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
  
  fonts:
    - family: DancingScript     
      fonts:
        - asset: assets/fonts/DancingScript-SemiBold.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf 
